# This is a development docker-compose.yml, don't use this one in production
version: "3.4"

x-golink-variables: &golink-variables
    GOPUBLISH_RUN_MODE: "dev"
    GOPUBLISH_REPOS_CONF: "test-data/sample_repos.yml"


services:
    golink:
        build: ./
        ports:
            - 9100:80
        depends_on:
            - redis
            - db
        environment: *golink-variables
        volumes:
            - repos:/repos/
            - ./:/golink/
            - ./docker/uwsgi_dev.ini:/etc/uwsgi/uwsgi.ini:ro

    worker:
        build:
            context: .
            dockerfile: docker_celery/Dockerfile
        depends_on:
            - redis
            - db
        entrypoint: python3
        command: /opt/celery_dev_launch.py
        environment: *golink-variables
        volumes:
            - repos:/repos/
            - ./:/golink/:ro
            - ./docker_celery/celery_dev_launch.py:/opt/celery_dev_launch.py:ro

    monitor:
        build:
            context: .
            dockerfile: docker_celery/Dockerfile
        ports:
            - "5555:5555"
        entrypoint: celery
        command: flower -A golink.tasks.celery --port=5555 --loglevel=info --autoreload
        depends_on:
            - redis
        environment: *golink-variables
        volumes:
            - ./:/golink/:ro

    redis:
        image: redis:4.0

    db:
        image: postgres:11-alpine
        environment:
          POSTGRES_PASSWORD: postgres

volumes:
    # A volume shared between golink app and worker
    repos:
