"""empty message

Revision ID: dfc6836fa9f1
Revises: 10ee1ed816e7
Create Date: 2022-02-15 10:23:27.966773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfc6836fa9f1'
down_revision = '10ee1ed816e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_tag_tag'), 'tag', ['tag'], unique=False)
    op.create_table('file_tag',
    sa.Column('file_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['published_file.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('file_id', 'tag_id')
    )
    op.add_column('published_file', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('published_file', sa.Column('version_of_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_published_file_version'), 'published_file', ['version'], unique=False)
    op.create_unique_constraint(None, 'published_file', ['id'])
    op.create_foreign_key(None, 'published_file', 'published_file', ['version_of_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'published_file', type_='foreignkey')
    op.drop_constraint(None, 'published_file', type_='unique')
    op.drop_index(op.f('ix_published_file_version'), table_name='published_file')
    op.drop_column('published_file', 'version_of_id')
    op.drop_column('published_file', 'version')
    op.drop_table('file_tag')
    op.drop_index(op.f('ix_tag_tag'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
